version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refactorian
      MYSQL_USER: refactorian
      MYSQL_PASSWORD: refactorian
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  db:
    container_name: db
    image: mariadb:10.7  # Usando a imagem do MariaDB em vez do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refactorian
      MYSQL_USER: refactorian
      MYSQL_PASSWORD: refactorian
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
